[workspace]
resolver = "2"

members = [
    "codegen",
    "rga3d",
    "cga3d",
    "cga3d_min",
    "cga3d_new",
    "examples/compile_to_spirv",
    "examples/hello_circle_wgsl",
    "examples/hello_circle_rust",
    "examples/broken_glsl/hello_circle_glsl",
    "examples/broken_glsl/debug_glsl",
    "examples/camera_and_instancing",
]
