[workspace]
resolver = "2"

members = [
    "codegen",
    "rga3d",
    "cga3d",
    "cga3d_min",
    "examples/compile_to_spirv",
    "examples/hello_circle_wgsl",
    "examples/hello_circle_glsl",
    "examples/hello_circle_rust",
    "examples/debug_glsl",
    "examples/camera_and_instancing",
]
