[package]
name = "codegen"
version = "0.2.1"
authors = ["Alexander Meißner <AlexanderMeissner@gmx.net>"]
edition = "2021"
publish = false

[dependencies]
naga = { version = "0.19.2", features = ["default", "glsl-in", "wgsl-in"] }