[package]
name = "codegen"
version = "0.2.1"
authors = ["Alexander Meißner <AlexanderMeissner@gmx.net>"]
edition = "2021"
publish = false

[dependencies]
naga = { version = "0.14.1", features = ["default", "glsl-in", "wgsl-in"] }
naga_oil = { version = "0.11.0", features = ["prune"] }