[package]
name = "codegen"
version = "0.2.1"
authors = ["Alexander Meißner <AlexanderMeissner@gmx.net>"]
edition = "2021"
publish = false

[dependencies]
naga = { version = "0.13.0", features = ["default", "glsl-in", "wgsl-out"] }
naga_oil = { version = "0.9.0", features = ["prune"] }
