[package]
name = "hello_circle_rust"
version = "0.1.0"
authors = ["Andrew Brown <Andrew.Brown.UNL@gmail.com>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
cga3d = { path = "../../libraries/cga3d" }